
name: APK_Uretici
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Al
        uses: actions/checkout@v3
      - name: Paketi Hazirla
        run: |
          echo "Voodoo Prototip v1" > build_info.txt
      - name: Dosyalari Disari Aktar
        uses: actions/upload-artifact@v3
        with:
          name: Voodoo_Oyun_Dosyalari
          path: |
            index.html
            build_info.txt
